[project]
name = "GePeTo"
version = "0.1.0"
description = "The most capable Discord bot"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "dspy>=2.6.27",
    "linkup-sdk>=0.2.8",
    "mlflow>=2.22.1",
]
